### ISSUE TITLE
Add command to reload VCD

### ISSUE THREAD

**Issue by Lramseyer** [Lramseyer/vaporview#12]
@hi0t
> I couldn't find a button or command to reload the vcd. If there is no such function, it would be a good idea to add it. If the data file has been updated, you have to close it, then open it and configure viewing again.

**Comment by Lramseyer** [comment]
Great idea! I just added it as a feature request and tagged you in it. Feel free to discuss there!

**Comment by Lramseyer** [comment]
I haven't forgotten about this! I am in the process of migrating to the node version of fs.read() which should allow me to get around the 2GB limit, as well as reloading vcd files.

There are 2 types of reloads:
  - "Fast" reload - where the file has been appended, and we only need to load in the new data
  - Total reload - where the vcd file was overwritten.

I assume that the "fast" reload is your intended use case?

**Comment by hi0t** [comment]
I rather meant a full reload. The scenario is as follows - we make some edits to the test bench (this may even be deleting and adding signals). After launching the modified test bench, we want to press a certain button that will reboot the vcd. Accordingly, the already configured signals in the current window should remain and simply update their state. It is likely that vaporview should try to find all the already configured signals by name in the updated vcd and display them again.

**Comment by Lramseyer** [comment]
OK, I'll look into full reload!

**Comment by Lramseyer** [comment]
Since this feature is the most requested feature, I am going to include this as a beta feature in [1.2.0](https://github.com/Lramseyer/vaporview/releases/tag/1.2.0-pre-release). It is not documented officially because I occasionally ran into issues reloading the variables, so I need to spend more time trying to figure out why.

To call this command, hit **Ctrl + Shift + P** and type **"Reload File(Beta)"** and that should reload the file.

I also made it easier to save and load viewer settings, by adding those commands to right click menu items, so hopefully this can work in the interim.

I'm going to leave this issue open until I have something that works reliably. That will probably come in a 1.2.1 release along with a few other small improvements.

**Comment by Lramseyer** [comment]
OK, this feature has officially been added to the 1.2.5 release. I wasn't sure where to put the command, so I put it in the Netlist view. It's also accessible via command entry **Ctrl + Shift + P** and type "Reload File" If anyone has another idea on how to implement it, I can add that in as well!
