### ISSUE TITLE
Different signals are displayed in different styles

### ISSUE THREAD

**Issue by narutozxp** [Lramseyer/vaporview#14]
Dear Lramseyer
This plug-in is easy to use, but the currently set style takes effect globally. It would be nice if each signal could have its own independent display style. Because many times, one signal needs to be displayed in hexadecimal, but other signals need to be displayed in decimal.

**Comment by Lramseyer** [comment]
Great idea! Something I have actually been planning on implementing, but haven't gotten around to yet. I was thinking of defaulting to hexadecimal, and using a context menu (right click menu) to set anything else.
Thoughts?

**Comment by narutozxp** [comment]
I think this is a good way

**Comment by Lramseyer** [comment]
OK, this should be fixed in the [1.0.1](https://github.com/Lramseyer/vaporview/releases/tag/release-candidate) release. Check it out!

**Comment by Lramseyer** [comment]
Sorry accidentally hit close!

**Comment by Lramseyer** [comment]
1.0.1 is released to the extension marketplace with this fix in place!
